apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: config-pr-generator
  title: Configuration PR Generator
  description: Generates a configuration YAML and creates a PR in GitHub
spec: 
  owner: jnkansah-va
  type: service

parameters:
  - title: Choose the language of your app
    required: 
      - language
    properties:
      language:
        title: Select language
        type: array
        minItems: 1
        items:
          type: string
          enum:
            - Python
            - Java
            - Ruby
            - Javascript
        uniqueItems: true
        ui:widget: checkboxes
    dependencies:
      language:
        allOf:
          - if:
              properties:
                language:
                  contains:
                    const: Python
            then:
              properties:
                pythonData:
                  title: Configure SecRel for Python Application
                  type: array
                  minItems: 1
                  items:
                    type: object
                    properties:
                      requirements:
                        title: Path to one or more requirements.txt
                        type: string
                      version:
                        title: Version
                        type: string


steps:
  - id: fetch-base
    name: Fetch Template
    action: fetch:template
    input: 
      url: ./skeleton
      targetPath: ./workspace

  - id: template-file
    name: Template the config.yml file
    action: template:file
    input: 
      templateFile: ./workspace/config.yaml
      target: ./workspace/config.yaml
      context: ${parameters}   
  - id: publish-pr
    name: Create PR with generated config
    action: publish:github:pull-request
    input:
      repoUrl: github.com?repo=${{ parameters.name }}
      defaultBranch: main
      description: Configuration file generated by backstage template
      
output:
  links:
    - title: View of GitHub
      url: ${{ steps.publish.output.remoteUrl }}