apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrel-config-generator
  title: SecRel Configuration Generator
  description: Generates a config.yml for SecRel with language configurations
spec:
  owner: jnkansah-va
  type: service
  parameters:
    - title: Select Application Language
      required:
        - language
      properties:
        language:
          title: Select language
          type: string
          enum:
            - Python
            - Java
            - Ruby
            - JavaScript
          ui:
            widget: select

    - title: Python Configuration
      if: '{{ parameters.language === "Python" }}'
      required:
        - pythonVersion
        - pythonRequirements
      properties:
        - name: pythonVersion
          title: Python version
          type: string
          description: Version of Python to use.
        - name: pythonRequirements
          title: Path to requirements.txt
          type: string
          description: Path to requirements.txt file.
    - title: Java Configuration
      if: ${{ parameters.language === 'Java' }}
      required:
        - javaVersion
        - javaPackageManager
        - javaBuildArgs
      properties:
        - name: javaVersion
          title: Java version
          type: string
          description: Version of Java to use
        - name: javaPackageManager
          title: Java Package Manager
          type: string
          description: Package manager for Java
          required: ${{ parameters.language === 'Java' }}
        - name: javaBuildArgs
          title: Java Build Arguments
          type: string
    - title: Ruby Configuration
      if: ${{ parameters.language === 'Ruby' }}
      required:
        - rubyVersion
        - rubyPaths
      properties:
        - name: rubyVersion
          title: Ruby version
          type: string
          description: Version of Ruby to use
        - name: rubyPaths
          title: Ruby Paths
          type: string
          description: Paths to Gemfiles
    - title: JavaScript Configuration
      if: ${{ parameters.language === 'JavaScript' }}
      required:
        - javascriptVersion
        - javascriptPackageManager
        - javascriptEnv
        - javascriptBuildArgs
        - javascriptPaths
      properties:
        - name: javascriptVersion
          title: Node.js Version
          type: string
          description: Version of Node.js
        - name: javascriptPackageManager
          title: JavaScript Package Manager
          type: string
          description: Package manager for JavaScript
        - name: javascriptEnv
          title: JavaScript Environment Variables
          type: string
          description: Environment variables for JavaScript.
        - name: javascriptBuildArgs
          title: JavaScript Build Arguments
          type: string
          description: Arguments for the JavaScript package manager.
        - name: javascriptPaths
          title: JavaScript Paths
          type: string
          description: Paths to directories with package.json files.

  steps:
    - id: log-selected-language
      name: Log Selected Language
      action: debug:log
      input:
        message: 'User selected language: ${{ parameters.language }}'
