parameters:
  - title: SecRel Configuration
    required:
      - language
    properties:
      language:
        title: Select language
        type: string
        enum:
          - Python
          - Java
          - Ruby
          - JavaScript
        ui:
          widget: select

      # Python-specific
      pythonVersion:
        title: Python version
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "Python" }}'

      pythonRequirements:
        title: Path to requirements.txt
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "Python" }}'

      # Java-specific
      javaVersion:
        title: Java version
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "Java" }}'

      javaPackageManager:
        title: Package manager (Maven, Gradle)
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "Java" }}'

      javaBuildArgs:
        title: Java build arguments
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "Java" }}'

      # Ruby-specific
      rubyVersion:
        title: Ruby version
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "Ruby" }}'

      rubyGemFilePath:
        title: Path to Gemfile
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "Ruby" }}'

      # JavaScript-specific
      jsVersion:
        title: JavaScript version
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "JavaScript" }}'

      jsPackageManager:
        title: Package manager (npm, yarn)
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "JavaScript" }}'

      jsPackageManagerVersion:
        title: Package manager version
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "JavaScript" }}'

      jsEnv:
        title: Environment variables
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "JavaScript" }}'

      jsBuildArgs:
        title: Build arguments
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "JavaScript" }}'

      jsPaths:
        title: Paths to dependencies
        type: string
        ui:field: Hidden
        ui:options:
          show: '{{ parameters.language === "JavaScript" }}'
