apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrel-configuration-generator
  title: SecRel Configuration File Generator
  description: Generates SecRel configuration file based on language of application.
spec:
  owner: jnkansah-va
  type: service
  parameters:
  - title: Select Language
    properties:
      language:
        type: string
        enum:
          - Python
          - JavaScript 

  - title: Python Options
    if:
      properties:
        language:
          const: "Python"
    then:
      properties:
        pythonVersion:
          type: string
          title: Python Version
        pythonRequirements:
          type: string
          title: Path to requirements.txt

  steps:
    - id: log-selected-language
      name: Log Selected Language
      action: debug:log
      input:
        message: 'User selected language: ${{ parameters.language }}' 