apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrel-config-generator
  title: SecRel Configuration Generator
  description: Generates a config.yml for SecRel with language configurations
spec: 
  owner: jnkansah-va
  type: service
parameters:
  - title: General Repo Info
    fields:
      - name: repository
        title: Repository Name
        type: string
        description: The name of the GitHub repository
        ui: { "widget": "text" }
      - name: defaultBranch
        title: Default Branch
        type: string
        description: Default branch of the repository.
        ui: { "widget": "text" }
  - title: Java Configuration
    fields:
      - name: javaEnabled
        title: Enable Java
        type: boolean
        default: false
      - name: javaVersion
        title: Java Version
        type: string
        description: Version of Java to use
        options: 
          - "8"
          - "11"
          - "17"
          - "21"
        default: "17"
        ui: { "widget": "text" }
      - name: javaPackageManager
        title: Java Package Manager
        type: string
        description: Package manager for Java
        options:
          - "maven"
          - "gradle"
        default: "maven"
        ui: { "widget": "select" }
      - name: javaBuildArguments
        title: Java Build Arguments
        type: string
        description: List of arguments for the Java package manager (comma-separated).
        ui: { "widget": "text" }
  - title: Python Configuration
    fields:
      - name: pythonEnabled
        title: Enable Python
        type: boolean
        default: false
      - name: pythonVersion
        title: Python Version
        type: string
        description: Version of Python to use.
        options:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        default: "3.9"
        ui: { "widget": "select" }
      - name: pythonRequirements
        title: Python Requirements Path
        type: string
        description: Path to Python requirements files (comma-separated)
        ui: { "widget": "text" }
  - title: JavaScript Configuration
    fields:
      - name: javascriptEnabled
        title: Enable JavaScript
        type: boolean
        default: false
      - name: javascriptPackageManager
        title: JavaScript Package Manager
        type: string
        description: Package Manager for JavaScript
        options:
          - "yarn"
          - "npm"
        default: "yarn"
        ui: { "widget": "select" }
      - name: javascriptPackageManagerVersion
        title: JavaScript Package Manager Version
        type: string
        description: Version of the JavaScript Package Manager/
        ui: { "widget": "text" }
      - name: javascriptVersion
        title: Node.js Version
        type: string
        description: Version of Node.js to use.
        options:
          - "14"
          - "16"
          - "18"
          - "20"
        default: "18"
        ui: { "widget": "select" }
      - name: javascriptEnv
        title: JavaScript Environment Variables
        type: string
        description: Environment variables for JavaScript (comma-separated, e.g., 'GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }}').
        ui: { "widget": "text" }
      - name: javascriptBuildArgs
        title: JavaScript Build Arguments
        type: string
        description: Arguments for the JavaScript package manager (comma-separated).
        ui: { "widget": "text" }
      - name: javascriptPaths
        title: JavaScript Paths
        type: string
        description: Paths to directories with package.json files (comma-separated).
        ui: { "widget": "text" }
  - title: Ruby Configuration
    fields: 
      - name: rubyEnabled
        title: Enable Ruby
        type: boolean
        default: false
      - name: rubyVersion
        title: Ruby Version
        type: string
        description: Version of Ruby to use.
        options:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        default: "3.2"
        ui: { "widget": "select" }
      - name: rubyPaths
        title: Ruby Paths
        type: string
        description: Paths to Gemfiles or directories containing Gemfiles (comma-separated.
        ui: { "widget": "text" }
        
#   - title: Choose the language of your app
#     required: 
#       - language
#     properties:
#       language:
#         title: Select language
#         type: array
#         minItems: 1
#         items:
#           type: string
#           enum:
#             - Python
#             - Java
#             - Ruby
#             - Javascript
#         uniqueItems: true
#         ui:widget: checkboxes
#     dependencies:
#       language:
#         allOf:
#           - if:
#               properties:
#                 language:
#                   contains:
#                     const: Python
#             then:
#               properties:
#                 pythonData:
#                   title: Configure SecRel for Python Application
#                   type: array
#                   minItems: 1
#                   items:
#                     type: object
#                     properties:
#                       requirements:
#                         title: Path to one or more requirements.txt
#                         type: string
#                       version:
#                         title: Version
#                         type: string


# steps:
#   - id: fetch-base
#     name: Fetch Template
#     action: fetch:template
#     input: 
#       url: ./skeleton
#       targetPath: ./workspace

#   - id: template-file
#     name: Template the config.yml file
#     action: template:file
#     input: 
#       templateFile: ./workspace/config.yaml
#       target: ./workspace/config.yaml
#       context: ${parameters}   
#   - id: publish-pr
#     name: Create PR with generated config
#     action: publish:github:pull-request
#     input:
#       repoUrl: github.com?repo=${{ parameters.name }}
#       defaultBranch: main
#       description: Configuration file generated by backstage template
      
# output:
#   links:
#     - title: View of GitHub
#       url: ${{ steps.publish.output.remoteUrl }}