apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrel-config-generator
  title: SecRel Configuration Generator
  description: Generates a config.yml for SecRel with language configurations

spec:
  owner: jnkansah-va
  type: service

  parameters:
    - title: Select Application Language
      required:
        - language
      properties:
        language:
          title: Select language
          type: string
          enum:
            - Python
            # - Java
            # - Ruby
            # - JavaScript

    - title: Python Configuration
      if: '{{ parameters.language == "Python" }}'
      required:
        - pythonVersion
        - pythonRequirements
      properties:
        pythonVersion:
          title: Python Version
          type: string
        pythonRequirements:
          title: Path to requirements.txt
          type: string

    # - title: Java Configuration
    #   if: '{{ parameters.language == "Java" }}'
    #   required:
    #     - javaVersion
    #     - javaPackageManager
    #   properties:
    #     javaVersion:
    #       title: Java Version
    #       type: string
    #     javaPackageManager:
    #       title: Package Manager (Maven, Gradle)
    #       type: string

    # - title: Ruby Configuration
    #   if: '{{ parameters.language == "Ruby" }}'
    #   required:
    #     - rubyVersion
    #     - rubyGemFilePath
    #   properties:
    #     rubyVersion:
    #       title: Ruby Version
    #       type: string
    #     rubyGemFilePath:
    #       title: Path to Gemfile
    #       type: string

    # - title: JavaScript Configuration
    #   if: '{{ parameters.language == "JavaScript" }}'
    #   required:
    #     - jsVersion
    #     - jsPackageManager
    #   properties:
    #     jsVersion:
    #       title: JavaScript Version
    #       type: string
    #     jsPackageManager:
    #       title: Package Manager (npm, yarn)
    #       type: string

    - title: GitHub Repository Info
      required:
        - owner
        - repository
        - defaultBranch
      properties:
        owner:
          title: GitHub Owner
          type: string
        repository:
          title: Repository Name
          type: string
        defaultBranch:
          title: Default Branch
          type: string

  steps:
    - id: log-selected-language
      name: Log Selected Language
      action: debug:log
      input:
        message: 'User selected language: ${{ parameters.language }}'

    - id: fetch-template
      name: Fetch config template
      action: fetch:template
      input: 
        url: https://github.com/department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline-onboarding-clone/blob/jnkansah-backstage-testing/templates/config-template.yml
        values:
          language: ${{ parameters.language }}
          pythonVersion: ${{ parameters.pythonVersion }}
          pythonRequirements: ${{ parameters.pythonRequirements }}
        targetPath: '.'

    - id: commit-and-push
      name: Commit and Push
      action: git:commit
      input:
        message: "Add SecRel pipeline configuration and DORA metrics workflow"
        author:
          name: "Tornado Service Account"
          email: "tornado-sa@example.com"
        workspacePath: .

    - id: create-pr
      name: Create Pull Request
      action: github:pull-request
      input:
        owner: ${{ parameters.owner }}
        repo: ${{ parameters.repository }}
        title: "SecRel Pipeline Onboarding"
        targetBranch: ${{ parameters.defaultBranch }}
        sourceBranch: "lhdi-onboarding-${{ execution.id }}"

  output:
    remoteUrl: ${{ steps.create-pr.output.remoteUrl }}
    pullRequestUrl: ${{ steps.create-pr.output.pullRequestUrl }}
