apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrel-configuration-generator
  title: SecRel Configuration File Generator
  description: Generates SecRel configuration file based on language of application.
spec:
  owner: jnkansah-va
  type: service
  parameters:
    - title: Choose language of app
      required:
        - language
      properties:
        language:
          title: Select language
          type: array
          minItems: 1
          items:
            type: string
            enum:
              - Python
              - Java
              - JavaScript
              - Ruby
          uniqueItems: true
          ui:widget: checkboxes
      dependencies:
        language:
          allOf:
            - if:
                properties:
                  languate:
                    contains:
                      const: Python
              then:
                properties:
                  pythonVersion:
                    title: Version of Python
                    type: string
                  pythonRequirements:
                    title: Path to requirements.txt
                    type: string
  steps:
    - id: log-selected-language
      name: Log Selected Language
      action: debug:log
      input:
        message: 'User selected language: ${{ parameters.language }}' 