apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrel-configuration-generator
  title: SecRel Configuration File Generator
  description: Generates SecRel configuration file based on language of application.
spec:
  owner: jnkansah-va
  type: service
  parameters:
  - title: Select Language
    properties:
      language:
        type: string
        enum:
          - Python
          - JavaScript
          - Java
          - Ruby 

  - title: Python Options
    if:
      properties:
        language:
          const: "Python"
    then:
      properties:
        pythonVersion:
          type: string
          title: Python Version
        pythonRequirements:
          type: string
          title: Path to requirements.txt
  - title: JavaScript Options
    if:
      properties:
        language:
          const: "JavaScript"
    then:
      properties:
        javascriptVersion:
          type: string
          title: JavaScript Version
        javascriptPackageManager:
          type: string
          title: Package Manager
        javascriptPackagerManagerVersion:
          type: string
          title: JavaScript Package Manager Version
        env:
          type: string
          title: Environment vars 
        javascriptBuildArgs:
          type: string
        javascriptPaths:
          type: string
  - title: Java Options
    if:
      properties:
        language:
          const: "Java"
    then:
      properties:
        javaVersion:
          type: string
          title: Java Version
        javaPackageManager:
          type: string
          title: Path to requirements.txt
        javaBuildArgs:
          type: string
          title: List of args that will be passed to the package manager
  - title: Ruby Options
    if:
      properties:
        language:
          const: "Ruby"
    then:
      properties:
        rubyVersion:
          type: string
          title: Ruby Version
        rubyPaths:
          type: string
          title: Path to Gemfiles

  steps:
    - id: log-selected-language
      name: Log Selected Language
      action: debug:log
      input:
        message: 'User selected language: ${{ parameters.language }}' 