apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: greetings
  title: Greetings via GitHub Workflow
  description: Triggers a GitHub Actions workflow that greets someone from a city
spec:
  owner: jnkansah-va
  type: automation

  parameters:
    - title: Who are we greeting?
      required:
        - name
        - city
      properties:
        name: 
          type: string
          description: The person's name
        city:
          type: string
          description: Where the person lives

  steps: 
    - id: trigger-hello
      name: Trigger GitHub Actions Workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?repo=backstage&owner=jnkansah-va
        workflowId: hello.yml
        branchOrTagName: main
        workflowInputs:
          input1: ${{ parameters.name }}
          input2: ${{ parameters.city }}

  output:
    text:
      - title: Workflow Triggered
        content: "Workflow to greet ${{ parameters.name }} from ${{ parameters.city }} has been triggered!"