apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: greetings
  title: Greetings via GitHub Workflow
  description: Triggers a GitHub Actions workflow that greets someone from a city
spec:
  owner: jnkansah-va
  type: automation

  parameters:
    - title: Who are we greeting?
      required:
        - name
        - city
      properties:
        name: 
          type: string
          description: The person's name
        city:
          type: string
          description: Where the person lives

  steps: 
    - id: trigger-hello
      name: Trigger GitHub Actions Workflow
      action: github:actions:dispatch
      input:
        repoUrl: https://api.github.com/repos/jnkansah-va/backstage/actions/workflows/hello.yml/dispatches
        workflowId: 156804120
        branchOrTagName: main
        workflowInputs:
          input1: name
          input2: city
        method: POST
        headers:
          Authorization: 'Bearer ${{ secrets.githubToken }}'
          Accept: 'application/vnd.github.v3+json'
        body:
          ref: main
          inputs:
            name: ${{ parameters.name }}
            city: ${{ parameters.city }}
  
  output:
    text:
      - title: "Workflow Triggered"
        content: "Workflow to greet ${{ parameters.name }} from ${{ parameters.city }} has been triggered!"