apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboarding-pipeline
  title: Secure Release Onboarding GitHub Issue
  description: Triggers the SecRel onboarding workflow
spec:
  owner: jnkansah-va
  type: automation

  parameters:
    - title: Workflow Inputs
      required:
        - systemName
        - systemDescription
        - slackChannel
        - email
        - teamName
        - repo
        - defaultBranch
      properties:
        systemName: 
          title: System Name
          type: string
          description: This name should match what is in eMASS for your registered System Name. 
          maxLength: 100
          pattern: "^[a-zA-Z0-9\\-() ]+$"
          ui:help: 'Hint: Limited to alphanumeric, -, (), and space characters.'
        systemDescription:
          title: System Description
          type: string
          description: Describe what your System does or will do
          ui:widget: textarea
          ui:options:
            rows: 10
          ui:help: 'Hint: This is used to provide Application Assessors and Privacy Officers with context that will help them better support your team.'
          ui:placeHolder: |
            MedPic Visualizer is a framework for rapid integration and evaluation of novel sources and use cases for patient-generated data (PGD). The DHP
            manages the import and storage of third-party PGD from vendors, such as Fitbit, manufacturers of other wearables, and other connected medical
            devices, and surfaces that data for use in clinical dashboards, population-scale research, etc.
        slackChannel:
          title: Your Team Slack Channel
          type: string
          description: Provide a public Slack channel name 
          ui:help: 'Omit # characters'
          ui:placeHolder: 'Ex: team-lasershark-alerts or team-lasershark'
        email:
          title: Your VA Email Address
          type: string
          description: This user will be granted permissions to manage teammate access to your project's data within security tools, and is required for SSO authentication.
          ui:placeHolder: 'firstname.lastname@va.gov'
        teamName:
          title: GitHub Team Name
          type: string
          description: VA GitHub team name will be used for naming convention for Kubernetes namespaces on LHDI, and provides continuity across alll tools, SSO authentication, and segmentation for your team's data.
          ui:placeHolder: 'lighthouse-lasershark'
        repo:
          title: GitHub Repository Name
          type: array
          description: The GitHub repository to onboard. You only need to provide the actual project name, not the organization.
          ui:placeHolder: 'lighthouse-medication-visualizer'
          items:
            type: object
            properties:
              name:
                type: string
        repoURL:
          title: GitHub Repository URL
          type: string
          description: URL to GitHub repository to onboard.
        defaultBranch:
          title: GitHub Repository Default Branch
          type: array
          description: Provide the trunk name that the SecRel pipeline will branch off of
          ui:placeHolder: 'main'
          items:
            type: string
        environment:
          type: string
          description: Pick the environment
          enum:
            - preview
            - development
            - production
  steps: 
    - id: trigger-onboarding-workflow
      name: Trigger Onboarding Workflow
      action: github:actions:dispatch
      input: 
        repoUrl: github.com?repo=lighthouse-tornado-secrel-pipeline-onboarding-clone&owner=department-of-veterans-affairs
        workflowId: onboarding.yml
        branchOrTagName: jnkansah-backstage-testing
        workflowInputs:
          systemName: ${{ parameters.systemName }}
          systemDescription: ${{ parameters.systemDescription }}
          slackChannel: ${{ parameters.slackChannel }}
          email: ${{ parameters.email }}
          teamName: ${{ parameters.teamName }}
          repo: ${{ parameters.repo | dump }} 
          repoURL: ${{ paramaters.repoURL }}
          defaultBranch: ${{ parameters.defaultBranch | dump }}

  output:
    text:
      - title: Workflow Triggered
        content: "The SecRel Onboarding workflow has been triggered via Code VA!"