apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: trigger-github-workflow
  title: Trigger GitHub Deploy Workflow
  description: Calls an existing GitHub Actions workflow
spec:
  owner: jnkansah-va
  type: automation

  parameters:
    - title: Trigger Options
      required: 
        - environment
      properties:
        environment:
          type: string
          enum: [staging, production]
          description: Which environment to deploy to?

  steps:
    - id: trigger
      name: Call GitHub Workflow
      action: fetch:call
      input:
        url: https://github.com/jnkansah-va/backstage/blob/main/.github/workflows/deploy.yml
        method: POST
        headers:
          Authorization: 'Bearer ${{ secrets.githubToken }}'
          Accept: 'application/vnd.github.v3+json'
        body:
          ref: main
          inputs:
            environment: ${{ parameters.environment }}

  output:
    text:
      - title: "GitHub Workflow Triggered"
        content:  "✅ GitHub workflow 'deploy.yml' has been triggered in 'my-org/my-repo' on 'main'."
