languages:
{%- if values.language == "Python" %}
  python:
    version: ${{ values.python.version }}
    requirements:
{%- for requirement in values.python.requirements %}
      - ${{ requirement }}
{%- endfor %}
{% endif %}

{%- if values.language == "Java" %}
  java:
    version: ${{ values.java.version }}
    package-manager: ${{ values.java.packageManager }}
    build-args:
{%- for arg in values.java.buildArgs %}
      - ${{ arg }}
{%- endfor %}
{% endif %}

{%- if values.language == "Javascript" %}
  javascript:
    package-manager: ${{ values.javascript.packageManager }}
    package-manager-version: ${{ values.javascript.packageManagerVersion }}
    version: ${{ values.javascript.version }}
    build-args:
{%- for arg in values.javascript.buildArgs %}
      - ${{ arg }}
{%- endfor %}
#     env:
# {%- for env in values.javascript.env %}
#       - "{{ env }}"
# {%- endfor %}

# {%- endfor %}
#     paths:
# {%- for path in values.javascript.paths %}
#       - ${{ path }}
# {%- endfor %}
{% endif %}

{%- if values.language == "Ruby" %}
  ruby:
    version: ${{ values.ruby.version }}
    paths:
{%- for gem in values.ruby.paths %}
      - ${{ gem }}
{%- endfor %}
{% endif %}
