languages:
  javascript:
    package-manager: ${{ values.javascript.packageManager }}
    package-manager-version: ${{ values.javascript.packageManagerVersion }}
    version: ${{ values.javascript.version }}
    env:
{%- for env in values.javascript.env %}
      - ${{ env }}
{%- endfor %}
    build-args:
{%- for arg in values.javascript.buildArgs %}
      - ${{ arg }}
{%- endfor %}
    paths:
{%- for path in values.javascript.paths %}
      - ${{ path }}
{%- endfor %}