languages:
  java:
    version: ${{ values.java.version }}
    package-manager: ${{ values.java.packageManager }}
    build-args:
{%- for arg in values.java.buildArgs %}
      - ${{ arg }}
{%- endfor %}
{% endif %}