languages:

  java:
    version: 
    package-manager: 
    build-args:




  python:
    version: 3.11
    requirements:

      - {{ req.strip() }}

      - {{ req.strip() }}




  javascript:
    package-manager: 
    package-manager-version: 
    version: 
    env:

      - {{ env }}

    build-args:

    paths:




  ruby:
    version: 
    paths:


