apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrel-pipeline-configuration
  title: Secrel Pipeline Configuration for Java app
  description: Generates the config file necessary to run SecRel and build your Java application. Pushed PR to GitHub repository. 
spec:
  owner: jnkansah-va
  type: service

  parameters:
    - title: GitHub Repository Settings
      type: object
      required: 
        - repo
        - defaultBranch
        - images
      properties:
        repo:
          title: Repository Name
          type: string
        defaultBranch:
          title: Default Branch Name (e.g., main, master)
          type: string
          default: main
        images:
          type: array
          title: Docker Images
          items:
            type: string

    - title: Java Settings
      type: object
      properties:
        javaVersion:
          type: string
          title: Java Version
        javaPackageManager:
          type: string
          title: Java Package Manager
        javaBuildArgs:
          type: array
          title: Args to pass to package manager
          items:
            type: string

  steps:
    - id: fetch-config-template
      name: Generate Config File
      action: fetch:template:file
      input:
        url: ./skeleton/java-config.yml
        targetPath: ./.github/secrel/config.yml
        values:
          java: 
            version: ${{ parameters.javaVersion }}
            packageManager: ${{ parameters.javaPackageManager }}
            buildArgs: ${{ parameters.javaBuildArgs }}

    - id: fetch-secrel-template
      name: Generate SecRel Reusable Workflow File
      action: fetch:template:file
      input:
        url: ./skeleton/secrel.yml
        targetPath: ./.github/workflows/secrel.yml
        values:
          defaultBranch: ${{ parameters.defaultBranch }}
          images: ${{ parameters.images }}

    - id: fetch-dora-template
      name: Generate DORA Reusable Workflow File
      action: fetch:template:file
      input:
        url: ./skeleton/dora-lead-time-for-changes.yml
        targetPath: ./.github/workflows/dora-lead-time-for-changles.yml

    - id: publish-to-github
      name: Create PR
      action: publish:github:pull-request
      input:
        repoUrl: "github.com?repo=${{ parameters.repo }}&owner=jnkansah-va"
        title: SecRel Pipeline Configuration
        description: "Adds SecRel configuration file, SecRel reusable workflow, and DORA workflow files"
        branchName: "lhdi-onboarding"
        targetBranch: ${{ parameters.defaultBranch }}

  output:
    links:
      - title: View config in PR
        path: ./.github/secrel/config.yml
      - title: View SecRel Workflow in PR
        path: ./.github/workflows/secrel.yml