apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrel-pipeline-configuration
  title: Secrel Pipeline Configuration for Python app 
  description: Generates the config file necessary to run SecRel and build your Python application. Pushed PR to GitHub repository. 
spec:
  owner: jnkansah-va
  type: service

  parameters:
    - title: GitHub Repository Settings
      type: object
      required: 
        - repo
        - defaultBranch
        - images
      properties:
        repo:
          title: Repository Name
          type: string
        defaultBranch:
          title: Default Branch Name (e.g., main, master)
          type: string
          default: main
        images:
          type: array
          title: Docker Images
          items:
            type: string

    - title: Python Settings
      type: object
      properties:
        pythonVersion:
          type: string
          title: Python Version
        pythonRequirements:
          type: array
          title: Path to requirements.txt
          items:
            type: string
            
  steps:
    - id: fetch-config-template
      name: Generate Config File
      action: fetch:template:file
      input:
        url: ./skeleton/python-config.yml
        targetPath: ./.github/secrel/config.yml
        values:
          python:
            version: ${{ parameters.pythonVersion }}
            requirements: ${{ parameters.pythonRequirements }}
    - id: fetch-secrel-template
      name: Generate SecRel Reusable Workflow File
      action: fetch:template:file
      input:
        url: ./skeleton/secrel.yml
        targetPath: ./.github/workflows/secrel.yml
        values:
          defaultBranch: ${{ parameters.defaultBranch }}
          images: ${{ parameters.images }}

    - id: fetch-dora-template
      name: Generate DORA Reusable Workflow File
      action: fetch:template:file
      input:
        url: ./skeleton/dora-lead-time-for-changes.yml
        targetPath: ./.github/workflows/dora-lead-time-for-changles.yml

    - id: publish-to-github
      name: Create PR
      action: publish:github:pull-request
      input:
        repoUrl: "github.com?repo=${{ parameters.repo }}&owner=department-of-veterans-affairs"
        title: SecRel Pipeline Configuration - Python Application 
        description: "Adds SecRel configuration file, SecRel reusable workflow, and DORA workflow files"
        branchName: 'lhdi-onboarding'
        targetBranch: ${{ parameters.defaultBranch }}

  output:
    links:
      - title: View config in PR
        path: ./.github/secrel/config.yml
      - title: View SecRel Workflow in PR
        path: ./.github/workflows/secrel.yml