apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrel-pipeline-configuration
  title: Secrel Pipeline Configuration
  description: Generates the config file necessary to run SecRel and build your application. Pushed PR to GitHub repository. 
spec:
  owner: jnkansah-va
  type: service

  parameters:
    - title: Select Application Language
      required:
        - language
      properties:
        language:
          title: Select language
          type: string
          enum:
            - Python
            - Java
            - Javascript
            - Ruby

    - title: Python Settings
      type: object
      properties:
        pythonVersion:
          type: string
          title: Python Version
        pythonRequirements:
          type: array
          title: Path to requirements.txt
          items:
            type: string
    - title: Java Settings
      type: object
      properties:
        javaVersion:
          type: string
          title: Java Version
        javaPackageManager:
          type: string
          title: Java Package Manager
        javaBuildArgs:
          type: array
          title: Args to pass to package manager
          items:
            type: string

    - title: JavaScript Settings
      type: object
      properties:
        javascriptVersion:
          type: string
          title: Javascript Version
        javascriptPackageManager:
          type: string
          title: Javascript Package Manager
        javascriptPackageManagerVersion:
          type: string
          title: Version of Javascript package manager
        javascriptEnv:
          type: array
          title: Environmental variables used by package manager
          items:
            type: string
        javascriptBuildArgs:
          type: array
          title: Args to pass to package manager
          items:
            type: string
        javascriptPaths:
          type: array
          title: Paths to dependencies
          items:
            type: string

    - title: Ruby Settings
      type: object
      properties:
        rubyVersion:
          type: string
          title: Ruby Version
        rubyPaths:
          type: array
          title: Path to gemfiles
          items:
            type: string

  steps:
    - id: fetch-template
      name: Generate Config File
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./.github/secrel
        values:
          language: ${{ parameters.language }}
          python:
            version: ${{ parameters.pythonVersion }}
            requirements: ${{ parameters.pythonRequirements }}
          java: 
            version: ${{ parameters.javaVersion }}
            packageManager: ${{ parameters.javaPackageManager }}
            buildArgs: ${{ parameters.javaBuildArgs }}
          javascript:
            version: ${{ parameters.javascriptVersion }}
            packageManager: ${{ parameters.javascriptPackageManager}}
            packageManagerVersion: ${{ parameters.javascriptPackageManagerVersion }}
            env: ${{ parameters.javascriptEnv }}
            buildArgs: ${{ parameters.javascriptBuildArgs }}
            paths: ${{ parameters.javascriptPaths }}
          ruby:
            version: ${{ parameters.rubyVersion }}
            paths: ${{ parameters.rubyPaths }}

    - id: generate-secrel-files
      name: Generate SecRel Files
      action: template
      input:
        template: |
          # secrel.yml - Workflow configuration
          name: SecRel Pipeline
          on:
            push:
              branches:
                - ${{ parameters.defaultBranch }}  # Trigger on pushes to the default branch
            workflow_dispatch: # Allows manual triggering
              inputs:
                logLevel:
                  description: 'Log level'
                  type: choice
                  options:
                    - 'info'
                    - 'warn'
                    - 'debug'
                  default: 'info'
          jobs:
            build:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout code
                  uses: actions/checkout@v4
                - name: Set up Python
                  uses: actions/setup-python@v4
                  with:
                    python-version: '3.9'
                - name: Install dependencies
                  run: pip install -r requirements.txt
                - name: Run security scans
                  #  Add your security scan steps here
                  run: echo "Running security scans..."
                - name: Build and Package
                  # Add your build steps
                  run: echo "Building and packaging..."
        targetFile: .github/workflows/secrel.yml

    - id: publish
      name: Create PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=jnkansah-va&repo=backstage
        branchName: secrel-test-${{ uuid }}
        title: SecRel Pipeline Configuration
        description: Adds SecRel config
        update: true

  output:
    links:
      - title: View config in PR
        path: ./github/secrel/config.yml
