apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: secrel-basic-python
  title: SecRel Python Config Generator (Test)
  description: Sanity check generates Python config only
spec:
  owner: jnkansah-va
  type: service

  parameters:
    - title: Select Application Language
      required:
        - language
      properties:
        language:
          title: Select language
          type: string
          enum:
            - Python
            - Java

    - title: Python Settings
      properties:
        pythonVersion:
          type: string
          title: Python Version
        pythonRequirements:
          type: string
          title: Path to requirements.txt

    - title: Java Settings
      properties:
        javaVersion:
          type: string
          title: Python Version
        javaPackageManager:
          type: string
          title: Path to requirements.txt
        javaBuildArgs:
          type: string
          title: Build Args
  steps:
    - id: fetch-template
      name: Render Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./target
        values:
          languages:
            python:
              version: ${{ parameters.pythonVersion }}
              requirements: ${{ parameters.pythonRequirements }}
            java: 
              version: ${{ parameters.javaVersion }}
              packageManager: ${{ parameters.packageManager }}
              buildArgs: ${{ parameters.buildArgs }}

    - id: publish
      name: Create PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=jnkansah-va&repo=backstage
        branchName: secrel-test-${{ uuid }}
        title: SecRel Python Config
        description: Adds Python config
        update: true

  output:
    links:
      - title: View config in PR
        path: ./target/config.yml
