languages:
{% if languages.java %}
  java:
    version: ${{ languages.java.version }}
    package-manager: ${{ languages.java.packageManager }}
    build-args:
{% for arg in languages.java.buildArgs %}
      - {{ arg }}
{% endfor %}
{% endif %}

{% if languages.python %}
  python:
    version: ${{ languages.pythonVersion }}
    requirements: ${{ languages.pythonRequirements }}
{% endif %}

{% if languages.javascript %}
  javascript:
    node-version: ${{ languages.javascript.nodeVersion }}
    package-manager: ${{ languages.javascript.packageManager }}
    build-script: ${{ languages.javascript.buildScript }}
{% endif %}

{% if languages.ruby %}
  ruby:
    version: ${{ languages.ruby.version }}
    paths:
{% for gem in languages.ruby.paths %}
      - {{ gem }}
{% endfor %}
{% endif %}
